### ISSUE TITLE
Anwender bekommt ein Überblick der Videos in seinem Kanal

### ISSUE THREAD

**Issue by suchja** [LernMoment/youtube-client#17]
Als Anwender möchte ich eine Auflistung aller Videos in meinem Kanal um daraus ein Video zur Bearbeitung auszuwählen.

Für jedes Video sollte angezeigt werden:

- [x] VideoID
- [x] Name
- [x] Veröffentlichungsstatus
- [x] Veröffentlichungsdatum oder Uploaddatum

**Comment by suchja** [comment]
@nocheinheinrich wenn du noch Fragen zu dieser User Story hast, dann kannst du sie einfach hier stellen. Natürlich ist es auch möglich hier Designentscheidungen oder andere Informationen speziell zu dieser User Story zu dokumentieren.

Im Menü rechts kannst du unter "Assignee" dich selbst eintragen und somit zeigen, dass du aktuell an dieser User Story arbeitest.

**Comment by nocheinheinrich** [comment]
Erledigt. Weiteres Feature wäre, dass der API-Key und die Channel-ID automatisch in einer weiteren Datei gespreichert werden, damit nicht immer alles neu ausgewählt werden muss.
